### ISSUE TITLE
Upscaling background

### ISSUE THREAD

**Issue by jlfernandezfernandez** [ivancea/hammerfight-io#23]
See differences from new (left) vs old (right)

![image](https://github.com/user-attachments/assets/9daa49fd-65c6-49a3-af88-cc36ab9f2c75)

New size have increased to 377KB vs 136KB. But now the image doesn’t have jagged edges that ruin the game’s visuals.

In next comment i'll attach the file compressed.
Regards, Jordi

**Comment by jlfernandezfernandez** [comment]
[background.jpg.zip](https://github.com/user-attachments/files/16349813/background.jpg.zip)

**Comment by ivancea** [comment]
Background is a placeholder; it won't be modified until a final design is ready.
